# Generated by Django 5.2.1 on 2025-06-01 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Programemr',
            new_name='Programmer',
        ),
    ]
