# Generated by Django 5.2.1 on 2025-06-05 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_programemr_programmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('chapter_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('paused', 'Paused'), ('finished', 'Finished')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Programmer',
        ),
        migrations.AddField(
            model_name='chapter',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='api.novel'),
        ),
    ]
