# Generated by Django 5.2.1 on 2025-06-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chapter_novel_delete_programmer_chapter_novel'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
