# Generated by Django 5.2.1 on 2025-06-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_author_gender_chapter_chapter_downloaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='image_url',
            field=models.URLField(default='https://storage.googleapis.com/audionovelas-bucket/generic_novel.jpg'),
        ),
    ]
