# Generated by Django 5.2.1 on 2025-06-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_novel_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='synopsis',
            field=models.TextField(blank=True, default='Sinopsis en preparación...'),
        ),
    ]
